-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 10:45:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema processo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema processo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `processo` DEFAULT CHARACTER SET utf8 ;
USE `processo` ;

-- -----------------------------------------------------
-- Table `processo`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processo`.`funcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processo`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processo`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `funcao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `funcao_id`),
  INDEX `fk_funcionario_funcao_idx` (`funcao_id` ASC),
  CONSTRAINT `fk_funcionario_funcao`
    FOREIGN KEY (`funcao_id`)
    REFERENCES `processo`.`funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processo`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processo`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `vel_maxima` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processo`.`rastreio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processo`.`rastreamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  `vel_registrada` FLOAT NOT NULL,
  `data_registro` DATETIME NOT NULL,
  `latitude` VARCHAR(20) NOT NULL,
  `longitude` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `funcionario_id`, `veiculo_id`),
  INDEX `fk_rastreio_funcionario1_idx` (`funcionario_id` ASC),
  INDEX `fk_rastreio_veiculo1_idx` (`veiculo_id` ASC),
  CONSTRAINT `fk_rastreio_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `processo`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rastreio_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `processo`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
